package vega;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

/** Coordinates Vega's user interface, command parsing, task list, and storage. */
public class Vega {
    private final Parser parser;

    private final Storage storage;

    private final TaskList tasks;

    private final Ui ui;

    private boolean isExitRequested;

    /**
     * Creates Vega using the given task data file.
     *
     * @param filePath Location of Vega's task data file.
     */
    public Vega(String filePath) {
        parser = new Parser();
        storage = new Storage(filePath);
        ui = new Ui();

        TaskList loadedTasks;
        try {
            loadedTasks = new TaskList(storage.loadTasks());
        } catch (VegaException e) {
            ui.showError(e.getMessage());
            loadedTasks = new TaskList();
        }
        tasks = loadedTasks;
        isExitRequested = false;
    }

    /** Starts Vega's command loop. */
    public void run() {
        ui.showWelcome();
        try (ui) {
            while (true) {
                String command = ui.readCommand();
                if (parser.getCommandWord(command).equals("bye")) {
                    break;
                }
                try {
                    handleCommand(command, ui);
                } catch (VegaException e) {
                    ui.showError(e.getMessage());
                }
            }
        }
        ui.showGoodbye();
    }

    /**
     * Runs Vega using its default data file.
     *
     * @param args Command-line arguments, which Vega does not use.
     */
    public static void main(String[] args) {
        new Vega("data/vega.txt").run();
    }

    /**
     * Returns the greeting used by the graphical interface.
     *
     * @return Vega's startup greeting.
     */
    public String getWelcomeMessage() {
        return Ui.getGreeting();
    }

    /**
     * Executes one command and returns the response for the graphical interface.
     *
     * @param input Command entered by the user.
     * @return Response generated by Vega.
     */
    public String getResponse(String input) {
        isExitRequested = false;
        ByteArrayOutputStream responseBuffer = new ByteArrayOutputStream();
        ByteArrayInputStream emptyInput = new ByteArrayInputStream(new byte[0]);
        try (PrintStream responseOutput = new PrintStream(responseBuffer, true, StandardCharsets.UTF_8);
                Ui responseUi = new Ui(emptyInput, responseOutput)) {
            String command = input.strip();
            if (parser.getCommandWord(command).equals("bye")) {
                responseUi.showGoodbye();
                isExitRequested = true;
            } else {
                handleCommand(command, responseUi);
            }
        } catch (VegaException e) {
            return "OOPS!!! " + e.getMessage();
        }
        return responseBuffer.toString(StandardCharsets.UTF_8).stripTrailing();
    }

    /**
     * Returns whether the latest GUI command asked Vega to exit.
     *
     * @return {@code true} after a valid {@code bye} command.
     */
    public boolean isExitRequested() {
        return isExitRequested;
    }

    private void handleCommand(String command, Ui activeUi) throws VegaException {
        String commandWord = parser.getCommandWord(command);
        String argument = parser.getArguments(command);
        switch (commandWord) {
            case "list":
                activeUi.showTaskList(tasks.asList());
                break;
            case "mark":
                updateTaskStatus(argument, true, activeUi);
                break;
            case "unmark":
                updateTaskStatus(argument, false, activeUi);
                break;
            case "delete":
                deleteTask(argument, activeUi);
                break;
            case "todo":
                if (argument.isEmpty()) {
                    throw new VegaException("A todo needs a description. Try: todo buy milk");
                }
                addTask(new Todo(argument), activeUi);
                break;
            case "deadline":
                addTask(parser.parseDeadline(argument), activeUi);
                break;
            case "event":
                addTask(parser.parseEvent(argument), activeUi);
                break;
            case "find":
                if (argument.isEmpty()) {
                    throw new VegaException("Please give a keyword to find. Try: find book");
                }
                activeUi.showMatchingTasks(tasks.find(argument));
                break;
            default:
                throw new VegaException("I don't recognise that command. "
                        + "Try todo, deadline, event, list, mark, unmark, delete, find, or bye.");
        }
    }

    private void updateTaskStatus(String argument, boolean shouldMark, Ui activeUi) throws VegaException {
        String commandWord = shouldMark ? "mark" : "unmark";
        int taskNumber = parser.parseTaskNumber(argument, commandWord);
        Task task = tasks.get(taskNumber);
        if (shouldMark) {
            task.markAsDone();
        } else {
            task.markAsNotDone();
        }
        storage.saveTasks(tasks.asList());
        activeUi.showTaskStatusChanged(task, shouldMark);
    }

    private void deleteTask(String argument, Ui activeUi) throws VegaException {
        int taskNumber = parser.parseTaskNumber(argument, "delete");
        Task removedTask = tasks.delete(taskNumber);
        storage.saveTasks(tasks.asList());
        activeUi.showTaskDeleted(removedTask, tasks.size());
    }

    private void addTask(Task task, Ui activeUi) throws VegaException {
        tasks.add(task);
        storage.saveTasks(tasks.asList());
        activeUi.showTaskAdded(task, tasks.size());
    }
}
